//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18034
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace nicojang.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int omokaru {
            get {
                return ((int)(this["omokaru"]));
            }
            set {
                this["omokaru"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public string onryo {
            get {
                return ((string)(this["onryo"]));
            }
            set {
                this["onryo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool otocheckboxbool {
            get {
                return ((bool)(this["otocheckboxbool"]));
            }
            set {
                this["otocheckboxbool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int burauza {
            get {
                return ((int)(this["burauza"]));
            }
            set {
                this["burauza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string zensetteipath {
            get {
                return ((string)(this["zensetteipath"]));
            }
            set {
                this["zensetteipath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("にこ")]
        public string zensettei {
            get {
                return ((string)(this["zensettei"]));
            }
            set {
                this["zensettei"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string h184 {
            get {
                return ((string)(this["h184"]));
            }
            set {
                this["h184"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<RSAKeyValue><Modulus>wl1z598Q65N1aOPnbF540l4In9wM3shVMIrfimcAM5gdCrawvaI4lPdlB+z" +
            "9BR5p51/o0qitCAEO6vy2mvMV9GHXjXohIwfVlosZGtI8Kv9t5wMWyl3F4aQ7j2KHewetMXYyXgfnoh3" +
            "VPLz+MU+Iu7rh/Pf+2IUOkq99oUpMEFM=</Modulus><Exponent>AQAB</Exponent></RSAKeyValu" +
            "e>")]
        public string publickye {
            get {
                return ((string)(this["publickye"]));
            }
            set {
                this["publickye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<RSAKeyValue><Modulus>wl1z598Q65N1aOPnbF540l4In9wM3shVMIrfimcAM5gdCrawvaI4lPdlB+z9BR5p51/o0qitCAEO6vy2mvMV9GHXjXohIwfVlosZGtI8Kv9t5wMWyl3F4aQ7j2KHewetMXYyXgfnoh3VPLz+MU+Iu7rh/Pf+2IUOkq99oUpMEFM=</Modulus><Exponent>AQAB</Exponent><P>4d9VGc0D9rAen6VExav0+csgeZorjraQqjiwXJlXZAe/G1JkJvKw8uXc7f5EyZlslyRgiZjw5cq0xEGuah5zRQ==</P><Q>3EpEPzdfvc13cu/+tcGbCKJSq0PmYWgfrP9EbvANN2Il83aaUu+03eWEzJuPEM6Xk691/HnfyfJa2M9SwZ6itw==</Q><DP>Ne8fIf8LYD9jwJk1F8Jcx7zSL1c56WT8nDjXG/VdobwbzQlactZmnEl4/LdHc6AYBusfxhtoAmbpzScl358PxQ==</DP><DQ>EzTecmyPimrpqTnHiW1R6RTOBGStJ3z+lgTDoLCJVnTWPj3vAqAnstkaFQTTGnIIwTWhIdw2aNManKCm5H7CTQ==</DQ><InverseQ>tELHyci/Sy2KLKCDUDhFECELIt5TRVRW792Rmo8Y6BqNgGjnaKpDQIZ8sdpcQpMHz/SRLaHSFnEOaZ/GQW7HUQ==</InverseQ><D>dX/PaPZmITQEv4M/TTkTa4FjT1jVAv0y2uSpXN8FtSsZK3fkAtAFyrCAiDkRgL2xIinN80P7TqJtJUvfDG817nha2gIGgfdddPNmKJEW14Vpd6J4wa2wbFJ1gkgTlPSf/plpj1Wo/ppIAflBOWpse+v/Ueh+2wFvhIBn4Kh4oQk=</D></RSAKeyValue>")]
        public string privateKey {
            get {
                return ((string)(this["privateKey"]));
            }
            set {
                this["privateKey"] = value;
            }
        }
    }
}
